/* 
	File name: stock_overflow_db
    Last edit: 03/26/2025
    Description: This file creates the database and stores the data for the management system Stockoverflow
*/

-- if 'STOCK_OVERFLOW_DB' database already exists, delete it
CREATE SCHEMA STOCK_OVERFLOW_DB;
USE STOCK_OVERFLOW_DB;
DROP DATABASE IF EXISTS STOCK_OVERFLOW_DB;

-- create the 'STOCK_OVERFLOW_DB' database
CREATE DATABASE STOCK_OVERFLOW_DB;
-- the current active database
USE STOCK_OVERFLOW_DB;

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
PRODUCT_NAME 				VARCHAR(100),
PRODUCT_PRICE				VARCHAR(50),
-- PRODUCT_TYPE				ENUM('Jewelry', 'Car', ''),  -- hmm wouldn't this just be name...
WIDTH 						FLOAT,
HEIGHT 						FLOAT,
DEPTH 						FLOAT,
WEIGHT 						FLOAT, -- define a range for these, have it in lbs.
SECURITY_LEVEL 				ENUM('Regular', 'High'), -- how to connect to other table? or not bc not key?
TEMPERATURE_REQUIREMENT 	ENUM('Regular', 'Cold'),  -- SET A RANGE FOR THIS LIKE 0-5 DEG CELSIUS
PRODUCT_ID 					INT NOT NULL,  -- DEFINE HOW MANY DIGITS, 9?
PRIMARY KEY (PRODUCT_ID)
);

DROP TABLE IF EXISTS WAREHOUSE;
CREATE TABLE WAREHOUSE (
-- WAREHOUSE_NAME 				VARCHAR(100),
MAX_CAPACITY 				FLOAT NOT NULL,
CURRENT_FILL 				FLOAT,   -- HOW FULL IS IT? SHOULD MAYBE BE HOW MUCH SPACE LEFT?
WIDTH 						FLOAT,
HEIGHT 						FLOAT,
DEPTH 						FLOAT,
LOCATION 					CHAR(100) NOT NULL,  -- ADDRESS BASICALLY
WAREHOUSE_ID 				INT NOT NULL,  -- DEFINE HOW MANY DIGITS
AVAILABILITY 				BOOLEAN, -- whether unit is available for use, full not full
TEMPERATURE_CONTROL 		ENUM('Regular', 'Cold'),
SECURITY_LEVEL 				ENUM('Regular', 'High'),
PRIMARY KEY (WAREHOUSE_ID),
PRICE_PER_SQ 				FLOAT NOT NULL,
FOREIGN KEY(PRICE_PER_SQ) REFERENCES PRICING_RATES (PRICE_PER_SQ),
UNIT_ID_NUMBER					INT,
FOREIGN KEY(UNIT_NUMBER) REFERENCES UNITS(UNIT_ID)
);



DROP TABLE IF EXISTS UNITS;
CREATE TABLE UNITS (
UNIT_ID						INT,
PRIMARY KEY(UNIT_ID),
PRICE						FLOAT NOT NULL,
HEIGHT						FLOAT NOT NULL,
WIDTH						FLOAT NOT NULL,
DEPTH						FLOAT NOT NULL
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (

ORDER_ID					INT,
PRIMARY KEY(ORDER_ID),
PRODUCT_ID					INT NOT NULL,
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CLIENT_ID					INT,
FOREIGN KEY(CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
UNIT_ID						INT,
FOREIGN KEY(UNIT_ID) REFERENCES UNITS(UNIT_ID),
QUANTITY					INT,
DATE						VARCHAR(50),  
TIME						VARCHAR(50)

);

-- users includes admin and client and employees 
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (

ROLE 						ENUM('ADMIN', 'EMPLOYEE', 'CLIENT'),
USER_ID 					INT NOT NULL,
PRIMARY KEY (USER_ID),
EMAIL 						VARCHAR(100) NOT NULL,  -- USER LOGIN EMAIL
PHONE_NUMBER				VARCHAR(50),
ADDRESS						VARCHAR(50),  -- NECESSARY???
PASSWORD_HASH VARCHAR(255) 	NOT NULL  -- FOR SECURITY

-- CLIENT_ID 					INT,
-- FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)

);

DROP TABLE IF EXISTS CLIENTS;
CREATE TABLE CLIENTS (
CLIENT_NAME 				CHAR(50) NOT NULL,
COMPANY_NAME 				CHAR(50),
PHONE_NUMBER 				CHAR(50),
EMAIL 						VARCHAR(50),
NR_OF_RENTED_UNITS 			INT NOT NULL,
CLIENT_ID 					INT, 
FOREIGN KEY (CLIENT_ID) REFERENCES USERS(USER_ID)   -- FIGURE OUT RANGE FOR THIS?
-- PRIMARY KEY CAN BE THE NAME MAYBE
);

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES (
EMPLOYEE_NAME 				CHAR(50),
PHONE_NUMBER 				CHAR(50),
EMAIL 						VARCHAR(50),
BIRTHDAY 					VARCHAR(100), 
SALARY 						VARCHAR(50),
Employee_ID 				INT NOT NULL,
FOREIGN KEY (Employee_ID) REFERENCES USERS(USER_ID)
-- PRIMARY KEY CAN BE NAME?
);