/* 
	File name: stock_overflow_db
    Last edit: 03/26/2025
    Description: This file creates the database and stores the data for the management system Stockoverflow
*/

-- if 'STOCK_OVERFLOW_DB' database already exists, delete it
CREATE SCHEMA STOCK_OVERFLOW_DB;
USE STOCK_OVERFLOW_DB;
DROP DATABASE IF EXISTS STOCK_OVERFLOW_DB;

-- create the 'STOCK_OVERFLOW_DB' database
CREATE DATABASE STOCK_OVERFLOW_DB;
-- the current active database
USE STOCK_OVERFLOW_DB;

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
PRODUCT_NAME 				VARCHAR(100),
PRODUCT_PRICE				VARCHAR(50),
-- PRODUCT_TYPE				ENUM('Jewelry', 'Car', ''),  -- hmm wouldn't this just be name...
WIDTH 						FLOAT,
HEIGHT 						FLOAT,
DEPTH 						FLOAT,
WEIGHT 						FLOAT, -- define a range for these, have it in lbs.
SECURITY_LEVEL 				ENUM('Regular', 'High'), -- how to connect to other table? or not bc not key?
TEMPERATURE_REQUIREMENT 	ENUM('Regular', 'Cold'),  -- SET A RANGE FOR THIS LIKE 0-5 DEG CELSIUS
PRODUCT_ID 					INT NOT NULL,  -- DEFINE HOW MANY DIGITS, 9?
PRIMARY KEY (PRODUCT_ID)
);

DROP TABLE IF EXISTS WAREHOUSE;
CREATE TABLE WAREHOUSE (
-- WAREHOUSE_NAME 				VARCHAR(100),
MAX_CAPACITY 				FLOAT NOT NULL,
CURRENT_FILL 				FLOAT,   -- HOW FULL IS IT? SHOULD MAYBE BE HOW MUCH SPACE LEFT?
WIDTH 						FLOAT,
HEIGHT 						FLOAT,
DEPTH 						FLOAT,
LOCATION 					CHAR(100) NOT NULL,  -- ADDRESS BASICALLY
WAREHOUSE_ID 				INT NOT NULL,  -- DEFINE HOW MANY DIGITS
AVAILABILITY 				BOOLEAN, -- whether unit is available for use, full not full
TEMPERATURE_CONTROL 		ENUM('Regular', 'Cold'),
SECURITY_LEVEL 				ENUM('Regular', 'High'),
PRIMARY KEY (WAREHOUSE_ID),
PRICE_PER_SQ 				FLOAT NOT NULL,
FOREIGN KEY(PRICE_PER_SQ) REFERENCES PRICING_RATES (PRICE_PER_SQ),
UNIT_ID_NUMBER					INT,
FOREIGN KEY(UNIT_NUMBER) REFERENCES UNITS(UNIT_ID)
);



DROP TABLE IF EXISTS UNITS;
CREATE TABLE UNITS (
UNIT_ID						INT,
PRIMARY KEY(UNIT_ID),
PRICE						FLOAT NOT NULL,
HEIGHT						FLOAT NOT NULL,
WIDTH						FLOAT NOT NULL,
DEPTH						FLOAT NOT NULL
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS (

ORDER_ID					INT,
PRIMARY KEY(ORDER_ID),
PRODUCT_ID					INT NOT NULL,
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CLIENT_ID					INT,
FOREIGN KEY(CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
UNIT_ID						INT,
FOREIGN KEY(UNIT_ID) REFERENCES UNITS(UNIT_ID),
QUANTITY					INT,
DATE						VARCHAR(50),  
TIME						VARCHAR(50)

);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    ROLE ENUM('ADMIN', 'EMPLOYEE', 'CLIENT'),
    USER_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (USER_ID),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(50),
    ADDRESS VARCHAR(50),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(100),
    IS_GOOGLE_ACCOUNT BOOLEAN DEFAULT FALSE
);


DROP TABLE IF EXISTS CLIENTS;
CREATE TABLE CLIENTS (
CLIENT_NAME 				CHAR(50) NOT NULL,
COMPANY_NAME 				CHAR(50),
PHONE_NUMBER 				CHAR(50),
EMAIL 						VARCHAR(50),
NR_OF_RENTED_UNITS 			INT NOT NULL,
CLIENT_ID 					INT, 
FOREIGN KEY (CLIENT_ID) REFERENCES USERS(USER_ID)   -- FIGURE OUT RANGE FOR THIS?
-- PRIMARY KEY CAN BE THE NAME MAYBE
);

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES (
EMPLOYEE_NAME 				CHAR(50),
PHONE_NUMBER 				CHAR(50),
EMAIL 						VARCHAR(50),
BIRTHDAY 					VARCHAR(100), 
SALARY 						VARCHAR(50),
Employee_ID 				INT NOT NULL,
FOREIGN KEY (Employee_ID) REFERENCES USERS(USER_ID)
-- PRIMARY KEY CAN BE NAME?
);



----------------------------------------------
DROP DATABASE IF EXISTS STOCK_OVERFLOW_DB;
CREATE DATABASE STOCK_OVERFLOW_DB;
USE STOCK_OVERFLOW_DB;

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS WAREHOUSE;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS UNITS;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROLE ENUM('EMPLOYEE', 'CLIENT') NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(50),
    ADDRESS VARCHAR(100),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(100),
    IS_GOOGLE_ACCOUNT BOOLEAN DEFAULT FALSE
);

CREATE TABLE CLIENTS (
    CLIENT_ID INT NOT NULL PRIMARY KEY,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    COMPANY_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(50),
    EMAIL VARCHAR(100),
    NR_OF_RENTED_UNITS INT DEFAULT 0,
    FOREIGN KEY (CLIENT_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(50),
    EMAIL VARCHAR(100),
    BIRTHDAY DATE,
    SALARY DECIMAL(10, 2),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE UNITS (
    UNIT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRICE DECIMAL(10, 2) NOT NULL,
    HEIGHT FLOAT NOT NULL,
    WIDTH FLOAT NOT NULL,
    DEPTH FLOAT NOT NULL
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
    WIDTH FLOAT,
    HEIGHT FLOAT,
    DEPTH FLOAT,
    WEIGHT FLOAT,
    SECURITY_LEVEL ENUM('Regular', 'High'),
    TEMPERATURE_REQUIREMENT ENUM('Regular', 'Cold')
);

CREATE TABLE WAREHOUSE (
    WAREHOUSE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MAX_CAPACITY FLOAT NOT NULL,
    CURRENT_FILL FLOAT DEFAULT 0,
    WIDTH FLOAT,
    HEIGHT FLOAT,
    DEPTH FLOAT,
    LOCATION VARCHAR(100) NOT NULL,
    AVAILABILITY BOOLEAN DEFAULT TRUE,
    TEMPERATURE_CONTROL ENUM('Regular', 'Cold'),
    SECURITY_LEVEL ENUM('Regular', 'High'),
    UNIT_ID INT,
    FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CLIENT_ID INT NOT NULL,
    UNIT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    ORDER_DATE DATE,
    ORDER_TIME TIME,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID)
);
