DROP DATABASE IF EXISTS STOCK_OVERFLOW_DB;
CREATE DATABASE STOCK_OVERFLOW_DB;
USE STOCK_OVERFLOW_DB;

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS WAREHOUSE;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS UNITS;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ROLE ENUM('EMPLOYEE', 'CLIENT') NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(50),
    ADDRESS VARCHAR(100),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(100),
    IS_GOOGLE_ACCOUNT BOOLEAN DEFAULT FALSE
);

CREATE TABLE CLIENTS (
    CLIENT_ID INT NOT NULL PRIMARY KEY,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    COMPANY_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(50),
    EMAIL VARCHAR(100),
    NR_OF_RENTED_UNITS INT DEFAULT 0,
    FOREIGN KEY (CLIENT_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(100),
    PHONE_NUMBER VARCHAR(50),
    EMAIL VARCHAR(100),
    BIRTHDAY DATE,
    SALARY DECIMAL(10, 2),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE UNITS (
    UNIT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRICE DECIMAL(10, 2) NOT NULL,
    HEIGHT FLOAT NOT NULL,
    WIDTH FLOAT NOT NULL,
    DEPTH FLOAT NOT NULL
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
    WIDTH FLOAT,
    HEIGHT FLOAT,
    DEPTH FLOAT,
    WEIGHT FLOAT,
    SECURITY_LEVEL ENUM('Regular', 'High'),
    TEMPERATURE_REQUIREMENT ENUM('Regular', 'Cold')
);

CREATE TABLE WAREHOUSE (
    WAREHOUSE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MAX_CAPACITY FLOAT NOT NULL,
    CURRENT_FILL FLOAT DEFAULT 0,
    WIDTH FLOAT,
    HEIGHT FLOAT,
    DEPTH FLOAT,
    LOCATION VARCHAR(100) NOT NULL,
    AVAILABILITY BOOLEAN DEFAULT TRUE,
    TEMPERATURE_CONTROL ENUM('Regular', 'Cold'),
    SECURITY_LEVEL ENUM('Regular', 'High'),
    UNIT_ID INT,
    FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CLIENT_ID INT NOT NULL,
    UNIT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    ORDER_DATE DATE,
    ORDER_TIME TIME,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID)
);
