//TermsPage.js
import React from 'react';
import { Container, Typography, Divider } from '@mui/material';

const TermsPage = () => {
  return (
    <Container maxWidth="md" style={{ marginTop: '2rem', paddingBottom: '2rem' }}>
      <Typography variant="h4" gutterBottom>
        Terms of Service
      </Typography>
      <Typography variant="subtitle1" gutterBottom>
        Effective Date: [5/1/2025]
      </Typography>
      <Typography paragraph>
        Welcome to ¬StockOverflow. These Terms of Service ("Terms") govern your access to and use of the ¬StockOverflow web application (the "Service"). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, please do not use the Service.
      </Typography>

      {[
        {
          title: '1. Overview',
          content: '¬StockOverflow is a warehouse management system that helps clients optimize their storage space using AI-powered layout planning. Our system processes user-provided data such as product details and storage requirements to deliver efficient storage recommendations through a web-based dashboard.',
        },
        {
          title: '2. Eligibility',
          content: 'You must be at least 18 years old to use our Service. By using the Service, you represent and warrant that you meet this requirement.',
        },
        {
          title: '3. User Accounts',
          content: 'To use certain features of the Service, you must register for an account and provide accurate and complete information including your email, phone number, and payment details. You are responsible for maintaining the confidentiality of your account credentials and for any activities that occur under your account.',
        },
        {
          title: '4. Data Collection and Use',
          content: `We collect the following personal information:
          \n• Email address
          \n• Phone number
          \n• Credit card information
          \n• Order and storage-related inputs
          \n\nThis information is used solely to provide and improve our Service, facilitate storage optimization, process orders, and maintain security. For more information, please review our Privacy Policy (link when available).`,
        },
        {
          title: '5. User-Generated Content',
          content: 'Users may submit data such as product lists, storage preferences, and orders ("User Content"). You retain ownership of your User Content but grant ¬StockOverflow a license to use, host, and process it solely to provide the Service. You are solely responsible for the accuracy and legality of any User Content you submit.',
        },
        {
          title: '6. Restrictions',
          content: `You agree not to:
          \n• Use the Service for any illegal or unauthorized purpose
          \n• Interfere with or disrupt the Service or servers
          \n• Reverse-engineer, decompile, or disassemble any part of the Service
          \n• Upload any data that is malicious, fraudulent, or violates intellectual property rights`,
        },
        {
          title: '7. AI-Generated Recommendations',
          content: 'Our Service provides recommendations using artificial intelligence based on user input. These recommendations are provided for informational purposes only and should not be solely relied upon for critical safety or regulatory decisions.',
        },
        {
          title: '8. Payment and Billing',
          content: 'While there is currently no paid version of the Service, we collect credit card details to process any relevant charges associated with storage-related transactions or services. By submitting payment information, you authorize us to process those charges.',
        },
        {
          title: '9. Termination',
          content: 'We may suspend or terminate your account and access to the Service if you violate these Terms. You may also stop using the Service at any time by deactivating your account.',
        },
        {
          title: '10. Disclaimer',
          content: 'The Service is provided "as is" without warranty of any kind, whether express or implied. We do not guarantee that the recommendations or layouts generated by the AI will be error-free, suitable for all needs, or meet specific legal or regulatory requirements.',
        },
        {
          title: '11. Limitation of Liability',
          content: 'To the maximum extent permitted by law, ¬StockOverflow shall not be liable for any indirect, incidental, special, or consequential damages arising out of or relating to your use of the Service.',
        },
        {
          title: '12. Changes to Terms',
          content: 'We may update these Terms from time to time. If changes are material, we will notify you. Continued use of the Service after changes become effective constitutes your acceptance of the revised Terms.',
        },
        {
          title: '13. Contact',
          content: 'If you have any questions about these Terms, please contact us at:\n📧 [nostockoverflows@gmail.com]',
        },
      ].map((section, index) => (
        <div key={index} style={{ marginBottom: '2rem' }}>
          <Divider />
          <Typography variant="h6" style={{ marginTop: '1rem' }}>
            {section.title}
          </Typography>
          <Typography variant="body1" style={{ whiteSpace: 'pre-line' }}>
            {section.content}
          </Typography>
        </div>
      ))}
    </Container>
  );
};

export default TermsPage;
